### ISSUE TITLE
Confirm follow up advice (ServiceRequest) only for colon cancer in examples

### ISSUE THREAD

**Issue by kridhaen** [hl7-be/public-health#12]
We will only give follow up advice for colon cancer (advice colonoscopy). The examples contain ServiceRequests for breast cancer with follow up advice (with text only). Should we remove these examples for breast cancer? Can we confirm that we will only use follow up advice for colon cancer and not for breast cancer so the examples can be removed or can the examples stay?

For colon cancer, we have a value set with Colonoscopy referenced from the ServiceRequest examples.
For breast cancer, will not have a value set. The current examples only contain patientInstruction = "Ga naar de arts die u hebt opgegeven bij het onderzoek, dit is uw huisarts of gynaecoloog of andere, voor een verwijsbrief voor bijkomend onderzoek.".

**Comment by bdc-ehealth** [comment]
WG: - we leave the example. - we will do something similar for breast cancer (SNOMED CT for GP/gynaecologist visit?)
