### ISSUE TITLE
Flow for identification of resources/episodes in Vitalink

### ISSUE THREAD

**Issue by kridhaen** [hl7-be/public-health#13]
If we share data (e.g. an episode) in FHIR to Vitalink, Vitalink will save the data and they will probably generate an identifier for the saved resource and returns it. The organisation that shared the data can save the identifier form the response and use that identifier for future updates of actions. What if the response fails, but the resource is correctly saved (e.g. network issues). How can we prevent in that case that we think the sharing failed en try it again, resulting in double resources?

Do we add an idenfitier created by the actors sharing the resources, so these actors can check if a resource exists with their identifier?  Should we add an identifier (e.g. see Instance: cvko-id in issue-1) to EpisodeOfCare so we can always check the existance of the episode resource? What's the best way to handle this and should we handle this, is is this to much of an edge case?

**Comment by bdc-ehealth** [comment]
Waiting for an identifier from Vitalink is probably not the best solution.

You can use an UUID (universally unique identifier), and if you do not receive an answer, you can send the same message (using  the same UUID) again until you receive an answer. In that way, the receiver can detect if you are sending the same message (he can check whether he already has a message with the same UUID).

**Comment by bdc-ehealth** [comment]
WG: we agree with the UUID proposal. This should be added to the IG in the guidance.
