### ISSUE TITLE
Visualization of resources with translations from English

### ISSUE THREAD

**Issue by kridhaen** [hl7-be/public-health#14]
The preferred visualization of the resources for the Flemish population based screening resources and contained data should be Dutch. 
We would prefer to avoid English terms in the visualization of the Flemish screening. A Dutch translation should be available if possible.

- How should we handle translations? 
- Who is responsible for the translation of the resources?
- Who should provide the translations?
- Is this something that can/should be defined in the IG?

**Comment by costateixeira** [comment]
I don't understand the scope of this: Do you mean the implementation guide
html site? The current language is entirely in English.

Internally, If you mean the element definitions, comments, values: FHIR has
a standard way to handle internationalization.
* Each element can have a "translation" extension, so we can have it in the
profiles (but what is the point?) and in the instances (why should we ?)
* all codes in our code systems already (should) have designations in the 3
languages
Multilanguage specifications are being handled in the publishing tooling, I
think in a few months we should have something.

I don't see the concept of visualization - what does this refer to?

Perhaps to discuss in the call?

Thanks

José

**Comment by kridhaen** [comment]
Some short extra explanation on scope and setting, but we can discuss it further in the next workgroup.

- Scope of this issue: 
> This is not about visualization of the IG itself (or the IG website), but visualization of the data that uses the resources defined in the IG by end users software that read and visualize the data (e.g. the health viewers or possible doctor software?).

- The setting for this issue:
> Currently we share health data in kmehr format (not FHIR) for the population screening. The data model follows closely the current logical model defined in this IG. In kmehr we had fields like next_invitation_indication that some health viewers (so end user software) visualized as "next invitation indication", so the full English term, while we would prefer the fields and data was translated. Same for other fields e.g. "screening year", "participation date" and data e.g. "coloncancer".

**Comment by bdc-ehealth** [comment]
There is an official (and medically approved) way to provide translations, and that is valid

- if you use SNOMED CT/LOINC codes. These codes are managed by the FAGG (NRC), and they have medically approved translations for the codes you use. 
- If you use free text, and you want the user to be able to see the text in his/her own language, then the sender is responsible for providing the translation in an additional extension specific for the language. 
- If you use another code (HL7 (FHIR) based) there are no translations available, and it is up to the displaying software to provide an applicable translation for the code in the desired language.

**Comment by bdc-ehealth** [comment]
WG: agrees with the methods proposed. They still have questions about the terminology in the resources themselves, but this is a similar problem in KMEHR. If needed this will be addressed in the guidance.
