### ISSUE TITLE
Request from CvKO: Add target group information for each screening type

### ISSUE THREAD

**Issue by kridhaen** [hl7-be/public-health#30]
New request from CvKO  that originates from the codes for BeCSPopulationScreeningNextInvitationType proposed in issue https://github.com/hl7-be/public-health/issues/26.

Situation:
- The code not-in-target-group in BeCSPopulationScreeningNextInvitationType had originally a display that contains the following text: "Invitations are from the year of your 50th birthday up to the year of your 69th birthday." This text is currently shared in KMEHR format.
- Each screening type has a different target group age interval. This means that we couldn't simply state 50 to 69 in general. 
- In issue 26 we proposed to change the display and template to "No invitations will be sent, you are not part of target group." while waiting for confirmation on the translations for each code from CvKO.

Problem:
- For BeCSPopulationScreeningNextInvitationType code not-in-target-group, we provide no information what defines the target group for the given screening and why the person is not in the target group if we use the display or template "No invitations will be sent, you are not part of target group.". CvKO want's to make it as clear as possible when or why a person will be invited to participate or not, so CvKO want to provide the following information on the target group.
    - Min age
    - max age
    - gender

Additional requirements:
- When there is a change in the definition of the target group, CvKO wants the change to be applied to all existing resources in FHIR. So the information about the target group should be a reference.
- The target group for a given screening will probably be different for each region (e.g. CvKO defines the target group for the screenings for the Flemish region.), so this target group will probably be unique for the Flemish region or CvKO. We will probably need to link the target group to a region (e.g. Flemish region) or organisation (e.g. CvKO) and we will have a target group for each screening.

Question:
- How can we best solve the stated problem/request?
    - Find a way to provide the information about the target group for the screening linked to the screening value set itself https://build.fhir.org/ig/hl7-be/public-health/branches/master/ValueSet-populationscreening-screening-vs.html. Are there existing resources that can be used?
    - Other options or opinions?

**Comment by costateixeira** [comment]
This seems close to decision support, and I suggest that in the first phase the scope should not be extended to handle this calculation: Suggest using the approach with concepts in the code system, and relative attributes (assuming they are not many different concepts - like less than 10).
In a later phase it would be interesting that the "guidance" will be extended to support creation of requests for cancer screening.

**Comment by bdc-ehealth** [comment]
ActivityDefinition/PlanDefinition could be an option...

EpisodeOfCare.referral -> ServiceRequest.code(Schedule next appointment) -> ServiceRequest.derivedFrom(ActivitDefinition)

**Comment by bdc-ehealth** [comment]
WG: the group considers it has too little information to set up a construction based on ActivityDefinition, or PlanDefinition (as suggested by chat by @costateixeira ). We will adopt the Communication resource to convey this information, and we will join it to the existing structure using the Communication.about field, which will refer to the EpisodeOfCare. The existing extension will remain in place.

**Comment by costateixeira** [comment]
There seems to be a misunderstanding of the proposals. I think the
reference to ActivityDefinition was not mine. Suggest clearing up the
additional confusion.

**Comment by bdc-ehealth** [comment]
Input by @costateixeira  as it was transmitted by @HanneVuegen
[Yesterday 10:18] Vuegen Hanne
Proposition from José (who has a docters appointment now so couldn't make it): Remove the extension for next screeningAdd a careplan that contains the activities for the patient - to be followed or notInclude a communication for informing the patient about the next visitThen we can look into the guidelines (I can perhaps show how the PlanDefinition works

**Comment by costateixeira** [comment]
Suggestion: 
* Remove the extension for next screening
* Include a communication for informing the patient about the next visit
* Add a careplan that contains the activities for the patient - to be followed or not
* Later, consider structuring the guidelines
