### ISSUE TITLE
Business Analysis CvKO (was: Q&A information)

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#32]
•	There is a duplicate value set.
•	There are typos and mixed languages (including in codes, which is causing the terminology validation to fail)
•	The number of profiles shows that the FHIR resources do not seem to be adequate:
o	 for example there are at least 2 profiles that, out of a resource, just use an extension  - which means we are using a resource, but we don’t use anything about that resource – which is a bad sign. 
•	There is a code system that does not seem to be well designed (the values it contains are languages but those value indicate another meaning than language). 
•	The guidance page does not say anything. Anyone that wants to read it would not find any information

**Comment by bdc-ehealth** [comment]
@vmichie Can you provide some functional text to add? The contents of the implementation guide is the responsibility of the HL7 WG and the project. We can only add information that is decided by the group.

**Comment by vmichie** [comment]
[BA_FHIR_CvKO_FHIRresources.docx](https://github.com/hl7-be/public-health/files/11271539/BA_FHIR_CvKO_FHIRresources.docx)
To be discussed on the next technical meeting on the 25th of April : Activity.detail.reasonReference

**Comment by bdc-ehealth** [comment]
@vmichie @kridhaen 
updated information after the WG meeting of 25/04/2023:
[BA_FHIR_CvKO_FHIRresources_V2.docx](https://github.com/hl7-be/public-health/files/11320995/BA_FHIR_CvKO_FHIRresources_V2.docx)
