### ISSUE TITLE
review by José Costa Teixeira

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#33]
https://docs.google.com/document/d/1vKXkf7u2bJh1QJ7nnLGJmCiImn713PuMxxWZtlOd45Q/edit

Overall cleanup:

http://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/
Original: https://build.fhir.org/ig/hl7-be/public-health/ 

TBD: Added “experimental=true” to profiles. 
No changes to the Logical model as that is for the Business to change.
Kept the resources as they are, in the parts that are not consensual. Cleanup of typos and duplicates and QA warnings.

TBD: Remove EpisodeOfCare as linking object - The scope of EpisodeOfCare is not perfectly clear to me: On one hand it says several episodes are possible for one screening, but on the other hand it also describes “(...) invitation took place in 2022, the next episode will be in 2024”.
The appearance of Episode as an extension to most resources while the Episode resource itself doesn’t contain any other MS element makes it more apparent that the Episode is underdocumented or unnecessary.
As it may be difficult  to have a consensus, we can just explain the options for implementers to work (noting that FHIR is an open standard, so the absence of a specification does not exclude functionality, rather defaults to the core standard). For now, commented all references to episode in examples and profiles.

Remove BeCSDisplayTemplate - as now indicated in the guidance page, the input needed to provide patient communication is standardized, but the actual communication is not standardized at this moment.

NextInvitationType VS and CS - removed the translated extensions for the templates, as per previous point.

Examples: Removed all links to Episode (see above)

Logical Model : rename to BeModelPopulationScreening (to follow initial convention)

PopulationScreeningVS - removed, was duplicate

BePopulationScreeningAppointment  - fixed typo in description, added MS (MustSupport) from the logical model to show the actual profiled resource. Added named slices (participant[patient] and participant[location])

Examples: Changed numeric slices of e.g. participant to named slices

BePopulationScreeningEncounter - added MS

BePopulationScreeningObservation - Added MS

BePopulationScreeningResultVS - changed results to EN designation - since profiles are in English, the validation would fail if they are in NL. Implementers can use the NL designations.

BePopulationScreeningFollowUp - 
Fixed wrong quotes in Description which was hijacking the  purpose definition.
Changed binding to example - extensible binds the codes more strictly, e.g. there was some discussion on the codes to use for intestinal / colon / colorectal cancer. Example bindings leaves the options more open in this phase.

BeVSPopulationScreeningType - reconciled with the duplicate and added the designation from SNOMED.

Transactions: used the term “Submit” instead of “send/update” in the diagram. “Submit” should cover both, and is rather not dependent on whether an update is really an update (for example when the submitter is not sure the previous submission was accepted).

Added diagram in Guidance to explain the link between the model and the agreed profiles.

Revamped guidance to be more indicative of the scope.

Cleanup of landing page to be “finished” - i.e. not necessarily as complete as I’d want, but without open paragraphs.

Transactions page - added links to actors, added some intro sentence, updated the FHIR resources - splitting into specific FHIR Resources for this profile AND other resources that may be (re)used from other BE or international specifications.

Overall improvement of page

Menu: changed menu for including Guidance above the Actors and transactions (removed “functional” for now).
Menu: Added link to Artifacts index. Not sure if we want to make the other artifacts less visible, or it is just because the sushi template did that - which in our case doesn’t seem good. The template does not enforce the menu.

Fixed link to history page (was pointing at another IG)

Added title and description to examples in the Artifact index.

Fixed some titles to add spaces, some typos.

Note: BK5 and BK6 are mentioning “normal” results but there is a follow-up for those. And from the description of the follow up resource, this should not exist - a negative result is said to not require any follow-up. Examples should be cleared.

**Comment by kridhaen** [comment]
In guidance: https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/guidance.html#data-exchange

- Service request is used to display follow up information, so the link to ServiceRequest in the diagram should start from followUp, see https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/StructureDefinition-be-populationscreening-follow-up.html (Communication resource will be used for nextInvitation info)

**Comment by costateixeira** [comment]
Updated in profiles
Will update in diagram if agreed and will make a new PR to commit to main
