### ISSUE TITLE
Belgian translation to nl-BE and fr-BE for 2 SNOMED CT codes

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#36]
If have register the request for
- 280415008 (Abnormal result) -> [BERMP-676](https://jira.ihtsdotools.org/browse/BERMP-676)
- 280413001 (Normal result) -> [BERMP-677](https://jira.ihtsdotools.org/browse/BERMP-677)

**Comment by bdc-ehealth** [comment]
beschikbaar: 

https://browser.ihtsdotools.org/?perspective=full&conceptId1=280415008&edition=MAIN/SNOMEDCT-BE/2023-05-15&release=&languages=en,nl,fr
https://browser.ihtsdotools.org/?perspective=full&conceptId1=280413001&edition=MAIN/SNOMEDCT-BE/2023-05-15&release=&languages=en,nl,fr

**Comment by vmichie** [comment]
The requested translations are present within SNOMED CT.
![2023-06-26 16_07_59-SNOMED CT - Normal result (qualifier value) en nog 2 andere pagina's - Werk - Mi](https://github.com/hl7-be/public-health/assets/113599686/87dee2df-b4cc-4681-9372-252af5a4193c)
![2023-06-26 16_09_35-SNOMED CT - Abnormal result (qualifier value) en nog 2 andere pagina's - Werk - ](https://github.com/hl7-be/public-health/assets/113599686/de38027e-83be-4112-9ec6-d9fbdfe4b3f4)
