### ISSUE TITLE
Add CarePlan at the logical model 

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#37]
Is it possible to add CarePlan at the logical model?
https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/guidance.html

**Comment by costateixeira** [comment]
added in https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/artifacts.html and 
https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/guidance.html 
Will make a separate PR to commit to main.
