### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#38]
We need to integrate Communication in the public health project.
https://hl7.org/fhir/r4b/communication.html -> https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/index.html

**Comment by costateixeira** [comment]
added in https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/artifacts.html
Will make a separate PR to commit to main.
