### ISSUE TITLE
comments from the meeting on 02/05/2023

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#40]
[BA_FHIR_CvKO_FHIRresources_V3.docx](https://github.com/hl7-be/public-health/files/11443991/BA_FHIR_CvKO_FHIRresources_V3.docx)

**Comment by vmichie** [comment]
[BA_FHIR_CvKO_FHIRresources_V3.docx](https://github.com/hl7-be/public-health/files/11485357/BA_FHIR_CvKO_FHIRresources_V3.docx)

**Comment by vmichie** [comment]
Version 10/05/2023
