### ISSUE TITLE
Some first thoughts on the model for PopulationScreening

### ISSUE THREAD

**Issue by tomdepreznxh** [hl7-be/public-health#41]
First, please excuse me if I'm providing info/questions in the wrong way, this is my first entry and I'm just introduced to this. 

Some first thoughts

1) I notice that BeModelPopulationScreening mentions of one entry per year, per screeningType. 
For breast cancer screening, there is a case were the examination has to be redone or a part (in case of a recall). This means a new appointment for the person (so it might be a state interesting to the person) . I'm not sure if it is the idea to go in such a detail, but at the moment it seems that the model isn't capable to handle this kind of information. 

2) a person can be excluded for a certain screeningType. It looks like this kind of information can't be shared. While this seems, to me, valuable information to the person. (a person can be excluded from a screeningType, even if no previous screening of that type has occured)

3) it feels not-100%-on-its-place to have the nextInvitation BackBoneElement in the BeModelPopulationScreening of a certain year. I see the need to give feedback if an"exclusion" in the following years is related to the screening of that year.  But this is not always the case. Wouldn't it be better to have a container per screeningtype which can hold specific information of that type, but not related to a certain screening year? This could include a general exclusion BackBoneElement and a nextInvitation estimation BackBoneElement.

4) long ago (previous model) I heard about difficulties to update info on "object" level. Eg to update certain kind of info, all objects needed to be deleted and inserted again. It looks like this isn't the case here. It seems that each object is individually accessible and updateable. (cfr 2.1.2 Resource uniqueness)

**Comment by SvenDhaens** [comment]
Hi Tom,

1. There is a use-case for 2 BEPHCarePlan's for the same year and thus that is  **necessary** (whenever a person with 2 SSN's gets merged this might happen) although this is rather an exception, it should be possible!
Besides that, for public-health, it **is** "possible" that there would be multiple BEPHAppointment's related to a single BEPHCarePlan, The appointment resources can be updated or multiple "activities" of BEPHAppointment can exist.

2. This case can be handled by a PopulationScreeningPlan with outcome-reference to a Communication resource.

3. The idea is that the exclusion is provided on a certain point in time, in that regard you can couple it to a BeModelPopulationScreening for a certain year, even if there is no other info provided. Viewers would always see this element as the "latest" BEPHCarePlan resource. Then there is also no need to update this earlier info should a newer BEPHCareplan be created.

4. previous model (you are referring to KMEHR structure?) yes, it was much more a case of completely rebuilding the resource. Here we can focus on a specific resource that changed. for example. only update the BEPHCommunication resource

**Comment by tomdepreznxh** [comment]
1. Tops.
2. I  might miss some information, where is the definition of "PopulationScreeningPlan
3. Okay
4. Okay"

**Comment by bdc-ehealth** [comment]
@tomdepreznxh : see https://build.fhir.org/ig/hl7-be/public-health/branches/qa-cleanup/StructureDefinition-be-populationscreening-plan.html

**Comment by tomdepreznxh** [comment]
thx. top. No further remarks / questions
