### ISSUE TITLE
BEPHCarePlan and BEPHAppointment

### ISSUE THREAD

**Issue by tomdepreznxh** [hl7-be/public-health#42]
Is BEPHAppointment a strict or loose contract to the subject?

Since in screening there is usually a loose 'invitation' and perhaps (or not) followed by a strict appointment.
A loose invitation might have eg no location or just a proposal of location
or just loose date as 'in year 2023' or 'period X-Y')
It is not yet 'confirmed' by the subject.

Are invitations included (for communication/information to the subject)? If so, will BEPHAppointment be used for both? 
If not, a specific BEPHInvitation resource might be interesting. (and also referred from BEPHCarePlan at activity

**Comment by SvenDhaens** [comment]
- On a BEPHAppointment Patient is required - Location is optional (usage in Colon-screening this "appointment" is in fact the invitation which resembles the test itself  sent through postage - no location -  no start date - only the field created would be filled in)
- The fact that it is confirmed or not by a patient is not a known factor to us, maybe we can do something about this in the future. For now we will provide the initial invitation dates received.
- This will be provided on the BEPHAppointment field "start" (= When appointment is to take place )
- BEPHAppointment you could say holds both concepts "appointments" in regards to breastcancer-screenings and "invitations to participate"(= letter with test-kit) in regards to Colon-screening

**Comment by tomdepreznxh** [comment]
Ok.
