### ISSUE TITLE
Failed installing IG (testing) - StructureDefinitions, ValueSets, NamingSystems with status draft

### ISSUE THREAD

**Issue by smals-bvv** [hl7-be/public-health#44]
Hi,

After the resources were published at the end of last month we are starting implementing this in Vitalink FHIR.
When loading the package in our HAPI framework, we have errors due to resources having the status 'draft'.
This causes failures on validations of the profile as some parts of the package is not loaded.

This is the list of resources labeled as draft:
- https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition/be-populationscreening-appointment
- https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition/be-populationscreening-encounter
- https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition/be-populationscreening-observation
- https://www.ehealth.fgov.be/standards/fhir/public-health/ValueSet/BeVSPopulationScreeningFollowUpAdvice
- https://www.ehealth.fgov.be/standards/fhir/public-health/ValueSet/be-vs-populationscreening-next-invitation-type
- https://www.ehealth.fgov.be/standards/fhir/public-health/ValueSet/be-vs-populationscreening-type
- https://www.ehealth.fgov.be/standards/fhir/public-health/ValueSet/be-vspopulationscreening-body-site-location
- https://www.ehealth.fgov.be/standards/fhir/public-health/NamingSystem/cvko-id

Is there a reason these are still on draft? Can this be adapted in a new version?

**Comment by bdc-ehealth** [comment]
@smals-bvv ,

if it bothers you, we can certainly consider to change the status. What is the particular reason that the resources cannot be loaded? We have never heard of any limitations regarding the status of the resources for loading them. Is that a standard feature of any of the major softwares, or is this something specific for Vitalink?

**Comment by bdc-ehealth** [comment]
@vmichie

Veerle, do you agree with changing the status to "active". I remember a conversation where you told us there would certainly be further modifications to the profiles after further testing.

**Comment by smals-bvv** [comment]
@bdc-ehealth It's the HAPI framework complaining about the draft status: it's not accepting it to load it in for resource validation.

**Comment by bdc-ehealth** [comment]
@smals-bvv ,

do you have a stack trace or error message?

**Comment by smals-bvv** [comment]
@smals-bvv It was one of the developers that had this issue. I asked to reproduce it (as in the meantime we have manually overwritten the statuses to active in the package we import).

Here is the stacktrace:
![stacktrace](https://github.com/hl7-be/public-health/assets/80458011/1af5ddc4-47e9-4e0c-be9a-f7d54fb2a35a)

Module: hapi-fhir-jpaserver-base-6.6.1

**Comment by bdc-ehealth** [comment]
@smals-bvv 

It is prohibited in this line in the hapifhir code. I think this is really weird. https://github.com/hapifhir/hapi-fhir/blob/a48c602f715a92a00a7f7b227c23b4624611376f/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java#L497

**Comment by vmichie** [comment]
@bdc-ehealth, there is no need to a draft status so you can change the status to active.
