### ISSUE TITLE
Issue in category:cancerScreeningType slice

### ISSUE THREAD

**Issue by smals-bvv** [hl7-be/public-health#46]
https://github.com/hl7-be/public-health/blob/40eebdf834e36c1182e125f86a88f38e6a346dda/input/fsh/profiles/BePopulationScreeningCarePlan.fsh#L22

The coding.system is expected to be https://www.ehealth.fgov.be/standards/fhir/public-health/ValueSet/be-vs-populationscreening-type and at the same time there is a Binding to that ValueSet with codes of the snomed CodeSystem.
This conflicts as both conditions can never be met at the same time.

Can this be confirmed and adapted?
@kridhaen @bdc-ehealth

**Comment by costateixeira** [comment]
you are correct. the slicing discriminator should not be the valueset. I'm
not sure how this happened, apologies.
The coding system should be SNOMED CT.

**Comment by bdc-ehealth** [comment]
@smals-bvv 

It seems clear to me that the publication of this IG without any technical tests was a mistake. This is the second issue that could have been prevented with a minimum of technical tests. I would like to refer to the issue that I filed some months before publication, in which I asked for technical tests: #24

**Comment by smals-bvv** [comment]
Unfortunately we discovered the same thing for BePopulationScreeningCommunication

https://github.com/hl7-be/public-health/blob/40eebdf834e36c1182e125f86a88f38e6a346dda/input/fsh/profiles/BePopulationScreeningCarePlan.fsh#L62
