### ISSUE TITLE
various remarks/questions on profiles/examples

### ISSUE THREAD

**Issue by PBACIN** [hl7-be/public-health#50]
Pour le profile https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-appointment.html
- l'élément "End" n'est pas mis comme must support mais utilisé dans les exemples
- les éléments "serviceCategory", "serviceType", "ReasonCode" sont mis en must support mais aucune trace dans les exemples, ni dans le data modèle. Est-ce que ce sera vraiment utilisé?

Pour le profile "https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-encounter.html"
- l'élément "type" est mis en must support, mais pas illustré dans les exemples. Est-ce que ce sera vraiment utilisé?
- l'élément subject devrait faire référence à un "be-patient"
- l'élément appointment devrait faire référence à un "be-populationscreening-appointment"

Pour le profile "https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-observation.html"
- l'élément encounter n'est pas mis comme must support
- l'élément encounter devrait faire référence à un "be-populationscreening-encounter"

Pour le profile https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-communication.html
- faut-il mettre des be-patient, be-organisation, ... pour les éléments "recipient", "sender" 

Pour le profile https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-follow-up.html
- l'élément "patientInstruction" est utilisé dans les exemples mais pas mis en must support

**Comment by vmichie** [comment]
WG (Philippe Baise, Bart Decuypere en Maxime Caucheteur) hebben beslist dat  MUST Support moet toegevoegd worden aan appointment END.

**Comment by vmichie** [comment]
MUST support mag verwijderd worden bij "serviceCategory", "serviceType", "ReasonCode"

**Comment by vmichie** [comment]
Mbt Encounter: "type" moet niet MUST SUPPORT zijn.

**Comment by vmichie** [comment]
Mbt encounter subject: moet patiënt vervangen worden door "be-patient"?

**Comment by vmichie** [comment]
Moet "be-populationscreening-appointment" opgenomen worden binnen de encounter?

**Comment by vmichie** [comment]
Binnen observation moet encounter als MUST SUPPORT ingesteld worden.

**Comment by vmichie** [comment]
Binnen observation moet de encounter verwijzen naar "be-populationscreening-encounter".

**Comment by vmichie** [comment]
Binnen communication moet bij de sender altijd BE-organisation zijn. De recipient moet enkel be-patient zijn of kan dit ook be-practitioner / be-practionerrole zijn?

**Comment by vmichie** [comment]
Moet binnen follow-up "patientinstruction" MUST SUPPORT worden?

**Comment by vmichie** [comment]
> WG (Philippe Baise, Bart Decuypere en Maxime Caucheteur) hebben beslist dat MUST Support moet toegevoegd worden aan appointment END.

29/04/2024 na feedback met Axians: we gingen ervan uit dat bij een START datum sowieso een END datum moest toegevoegd worden. Is dit correct? Binnen deze FHIR resource moet er eigenlijk geen END datum worden meegegeven, focus ligt op START datum hierdoor is START en END-datum hetzelfde.

**Comment by vmichie** [comment]
> MUST support mag verwijderd worden bij "serviceCategory", "serviceType", "ReasonCode"

29/04/2024: Axians gaat hiermee akkoord, MUST support mag verwijderd worden bij serviceCategory, serviceType en reasonCode.

**Comment by vmichie** [comment]
> Mbt Encounter: "type" moet niet MUST SUPPORT zijn.

29/04/2024: In samenspraak met Axians: het element type binnen encounter mag de flag MUST support verwijderd worden.

**Comment by vmichie** [comment]
> Mbt encounter subject: moet patiënt vervangen worden door "be-patient"?

29/04/2024: mag inderdaad vastgelegd als BE-Patient gezien Heracles FHIR steeds een BE-patient uitstuurt en de andere resources ook steeds verwijzen naar BE-patient en zo is er uniformiteit.

**Comment by vmichie** [comment]
> Moet "be-populationscreening-appointment" opgenomen worden binnen de encounter?

29/04/2024: momenteel wordt appointment niet ingevuld bij encounter maar indien dit in de toekomst zal gebruikt worden mag dit verwijzen naar be-populationscreening-appointment.

**Comment by vmichie** [comment]
> Binnen observation moet encounter als MUST SUPPORT ingesteld worden.

29/04/2024: het element encounter mag de flag MUST SUPPORT krijgen binnen observation.

**Comment by vmichie** [comment]
> Binnen observation moet de encounter verwijzen naar "be-populationscreening-encounter".

29/04/2024: er zal nooit naar een andere waarneming gezocht worden dan naar deze mbt bevolkingsonderzoeken, hierdoor mag het element encoutner verwijzen naar be-populationscreening-encouter binnen observation.

**Comment by vmichie** [comment]
> Binnen communication moet bij de sender altijd BE-organisation zijn. De recipient moet enkel be-patient zijn of kan dit ook be-practitioner / be-practionerrole zijn?

29/04/2024: binnen communicatie is de sender altijd BE-organisation nl. CvKO. Binnen het element recipient wordt énkel be-patient gebruikt. Momenteel is er geen zicht op plannen dat dit zal gewijzigd worden naar bijv. be-practitioner / be-practionerrole.

**Comment by vmichie** [comment]
> Moet binnen follow-up "patientinstruction" MUST SUPPORT worden?

29/04/2024: in het voorbeeld mag de patientinstruction verwijderd worden gezien de instructies via communication meegegeven worden. Dus patientinstruction mag de flag MUST SUPPORT niet krijgen. Het voorbeeld "ServiceRequest/ColorectalCancerScreeningFollowUpExample mag aangepast worden nl. het verwijderen van patientinstruction. De andere voorbeelden ServiceRequest/BK-5-example-advice-1, ServcieRequest/BK-6-example-advice en ServcieRequest/BreastCancerScreeningFollowUpExample mogen verwijderd worden om verwarring te vermijden.

**Comment by kridhaen** [comment]
> > WG (Philippe Baise, Bart Decuypere en Maxime Caucheteur) hebben beslist dat MUST Support moet toegevoegd worden aan appointment END.
> 
> 29/04/2024 na feedback met Axians: we gingen ervan uit dat bij een START datum sowieso een END datum moest toegevoegd worden. Is dit correct? Binnen deze FHIR resource moet er eigenlijk geen END datum worden meegegeven, focus ligt op START datum hierdoor is START en END-datum hetzelfde.

Zie app-2 Invariants in https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-appointment-definitions.html#Appointment

**Comment by bdc-ehealth** [comment]
@kridhaen Thanks Kurt for your feedback. With your remarks we will consider the decision of the WG final. I will modify the resources.
