### ISSUE TITLE
be-populationscreening-appointment patient slice

### ISSUE THREAD

**Issue by smals-maxca** [hl7-be/public-health#53]
Regarding Public Health Appointment resource, our HAPI framework has an issue validating the slice for patient correctly because there is no reference to a BePatient the moment the request comes in: it’s a logical identifier to a pseudonym.
Is it possible to make the constraint less strict ? Maybe with something like BeLiteralOrLogicalReference as when it comes in it is a logical reference.
Thank you.

**Comment by bdc-ehealth** [comment]
@smals-maxca ,

can you please copy-and-paste the error message + the message that was validated? Be aware also that HAPIFHIR has a lot of options to customize validation, but let's first check what the issue is.

**Comment by smals-maxca** [comment]
Here is the error message: 
[response.json](https://github.com/hl7-be/public-health/files/15128103/response.json)

Here is the participant.actor patient inside the Appointment resource:
[message.json](https://github.com/hl7-be/public-health/files/15128131/message.json)

**Comment by bdc-ehealth** [comment]
@smals-maxca 

Hello Maxime,

I checked your file, and the way in which the slicing is defined requires you to provide the participant as a contained resource. I can change the way the slicing works, but you will have to provide the actor.type in that case: I will have to make it mandatory.

**Comment by bdc-ehealth** [comment]
@vmichie, can you check this? Is this OK from a busines perspective to change the slicing?

**Comment by kridhaen** [comment]
@vmichie From a busines perspective it is OK to change the slicing. 
@smals-maxca @bdc-ehealth Currently we already provide the actor type "Patient" for the pseudonym to Vitalink. As far as i know, the Patiënt will never be a contained resource because the Patiënt is managed by Vitalink.

- Will the mandatory type only apply to the Patient actor or also to the contained Location resource actor?

- Will the following example be correct or does it need to be changed after the change to the slicing?

Current example participant list for Appointment breast cancer:
```
"contained": [ {
        "resourceType": "Location",
        "id": "1",
        "name": "xxx",
        "address": {
          "line": [ "xxx", "xxx" ],
          "city": "x",
          "postalCode": "xxx",
          "country": "BEL"
        }
      } ],
"participant": [ {
        "actor": {
          "type": "Patient",
          "identifier": {
            "system": "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/ssin",
            "value": "xxx",
            "_value": {
              "extension": [ {
                "url": "https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-pseudonymization",
                "extension": [ {
                  "url": "marker",
                  "valueBoolean": true
                } ]
              } ]
            }
          }
        },
        "status": "accepted"
      }, {
        "actor": {
          "reference": "#1"
        },
        "status": "accepted"
      } ]
    }
```
If the above example is also correct after the change, the change will have no impact on our current usage.

**Comment by bdc-ehealth** [comment]
@kridhaen actor.type will be mandatory, so the example above will no longer be correct.

**Comment by kridhaen** [comment]
@bdc-ehealth Ok, so adding the type to the contained location resource in the following example will be correct after the change?
```
"contained": [ {
        "resourceType": "Location",
        "id": "1",
        "name": "xxx",
        "address": {
          "line": [ "xxx", "xxx" ],
          "city": "x",
          "postalCode": "xxx",
          "country": "BEL"
        }
      } ],
"participant": [ {
        "actor": {
          "type": "Patient",
          "identifier": {
            "system": "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/ssin",
            "value": "xxx",
            "_value": {
              "extension": [ {
                "url": "https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-pseudonymization",
                "extension": [ {
                  "url": "marker",
                  "valueBoolean": true
                } ]
              } ]
            }
          }
        },
        "status": "accepted"
      }, {
        "actor": {
          "type": "Location",
          "reference": "#1"
        },
        "status": "accepted"
      } ]
    }
```

**Comment by bdc-ehealth** [comment]
@kridhaen : That is the aim. If you can agree with this, I will test it through, and check that there is not other impact.

**Comment by kridhaen** [comment]
@bdc-ehealth Ok, looks good to me

**Comment by smals-maxca** [comment]
@bdc-ehealth For us actor.type can be mandatory. It also looks OK to me.

**Comment by bdc-ehealth** [comment]
@kridhaen , @smals-maxca ,

There are no other changes beyond what was expected. Check the examples. You can check on the master branch.
