### ISSUE TITLE
Logical Model: BeBevolkingsonderzoek.patient -> Patient becomes BePatient.

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#6]

**Comment by costateixeira** [comment]
We should first create a logical model for the BePatient

**Comment by bdc-ehealth** [comment]
WG: we ask the core WG to add a logical model for BePatient.

**Comment by costateixeira** [comment]
The use of physical data types / resources in logical models is not really orthodox and should be cleaned up everywhere. 
However, we don't mind - at this phase - to do in this project what has been done for others, which is that the logical data model uses "physical" data types and resources such as Identifier, Patient, ...
Decision: For allowing implementations while that model doesn't exist yet, we agree to continue using the Patient resource in the logical model.
This should be revisited when the issue mentioned above is handled.
