### ISSUE TITLE
Logical Model: result according to LabResult standard?

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#7]

**Comment by bdc-ehealth** [comment]
WG: we prefer to depend on BeObservation. We should ask Core Clinical workgroup to create the logical model.

**Comment by costateixeira** [comment]
https://ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition-be-observation.html#tabs-diff

BeObservation has:
1. predefined slices for LOINC and SNOMED
2. Must Support on code
3. mandatory performer

Are all these OK for us?

**Comment by costateixeira** [comment]
Discussion:
We can use BeObservation:
1. LOINC and SNOMED are slices and not mandatory, so it's good to use that.
2. Code is mandatory anyway, so we don't have an issue with it being Must Support
3. mandatory performer - we will always send "CvKO" as a performer in the Observation

**Comment by bdc-ehealth** [comment]
WG: we will use BeObservation to represent the results of the screening.
